services:

  uptime-kuma:
    image: louislam/uptime-kuma:2.4.0
    container_name: uptime-kuma
    volumes:
      - ./uptime-kuma:/app/data
    ports:
      - "8200:3001"
    restart: unless-stopped
    environment:
      - TZ=Europe/Madrid
